# Generated by Django 3.0.4 on 2021-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
                ('estado', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('curriculum_Vitae', models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
            ],
        ),
    ]
