# Generated by Django 3.0.4 on 2021-04-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Detalle_Venta', '0001_initial'),
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venta.Venta'),
        ),
    ]
